### ISSUE TITLE
Conflicts with ALE lint message virtual text

### ISSUE THREAD

**Issue by mrjones2014** [f-person/git-blame.nvim#25]
There should be an option to not show if the line currently has an ALE message and ALE is configured to use virtualtext

**Comment by mrjones2014** [comment]
See how the ALE message flashes for a sec when you move the cursor -- I think the VirtualText from this plugin is hiding the VirtualText from ALE which should have higher priority


https://user-images.githubusercontent.com/8648891/114047329-9ee02b00-9857-11eb-9b74-2fc2c069157b.mov

**Comment by f-person** [comment]
I'm not sure how we can check if there is a way to do that (took a quick look at [Nvim API](https://neovim.io/doc/user/api.html), didn't find anything). Something that comes to my mind is an option to be able to set the namespace id from the init script, so that you could give the plugin lower id than ale has.

**Comment by mrjones2014** [comment]
hmmm, yeah I took a quick look through ALE's help file and didn't find anything that seemed relevant either.

**Comment by f-person** [comment]
I don't think there's a good way to fix this. I believe you can configure ALE to use other methods for displaying virtual text. For example, showing a popup window with the message or in the status bar.
