### ISSUE TITLE
[Feature] activate only on keybind

### ISSUE THREAD

**Issue by Seirdy** [f-person/git-blame.nvim#3]
The plugin https://github.com/rhysd/git-messenger.vim is similar to this one, but has two main differences:

1. It activates on a keybind (default: `<leader>gm`)
2. It displays git information in a floating window

Personally, I'm to too interested in having a popup window; however, having git-blame only appear on-demand is the main think keeping me on git-messenger.

I could implement this in the coming week if you're interested.

**Comment by f-person** [comment]
Do I understand correct that you want a way to enable/disable the plugin? If yes, I can make a toggle function tomorrow and also create a `:ToggleGitBlame` (or something like that) command, which you then can map to a keybinding

**Comment by Seirdy** [comment]
Well, not exactly. I don't want vtext to follow me around as I move my 
cursor; I just want git-blame information to show up when I call that 
function and disappear as soon as I switch modes or move my cursor, like 
a diagnostic window on many setups.  So it's not quite like disabling 
and enabling the plugin, if that makes sense.

**Comment by f-person** [comment]
Got it. I think that it would make more sense to implement what you want in a new plugin instead of extending this one as there's not much code that will be reused because of the way this plugin works - it loads blames for the whole file instead of requesting blame info for every line on cursor change. It would be better for something like git-messenger to load info for the current line only when it has been requested.

If you think the same way, we can close the issue. If not, you can implement this feature and we can merge it if it fits the code base.

**Comment by Seirdy** [comment]
Agreed. I'll close it.
