### ISSUE TITLE
Feature: Open the commit URL

### ISSUE THREAD

**Issue by eleijonmarck** [f-person/git-blame.nvim#33]
**why and what**
I would love to be able to go from the line to github link. See the https://marketplace.visualstudio.com/items?itemName=waderyan.gitblame

This enables showing the git commit, but also go to the url.

combingin
```vimscript
  Plug 'tpope/vim-fugitive' " git
  Plug 'tpope/vim-rhubarb' " makes so that git can be opened using GBrowse
```

**Comment by eleijonmarck** [comment]
yea understand that.
It is such a nice feature though. How do you go to a blame commit?

**Comment by f-person** [comment]
This is something to consider even if it's closed right now :)
I'll give it some thought sometime in the future

**Comment by f-person** [comment]
@eleijonmarck I hope the solution I pushed is what you needed :)

**Comment by ranelpadon** [comment]
@f-person I was using [blamer.nvim](https://github.com/APZelos/blamer.nvim) for a long time, but replaced it with `git-blame.nvim` now since I wanted this `:GitBlameCopySHA` feature for a long time! The copied SHA is then used to open our GitLab link in browser. Upon digging further, I find out that you have `:GitBlameOpenCommitURL` also which is even more efficient since I don't need to copy the SHA and paste it in our GitLab URL anymore! 

Thanks a lot for this kickass plugin, and thanks to @eleijonmarck for requesting this feature. :)

**Comment by f-person** [comment]
@ranelpadon thank you very much for kind words, I really appreciate them! I'm glad to know that you like using `git-blame.nvim`, I put lots of love into it 💜
