### ISSUE TITLE
"Not Committed Yet" on Windows

### ISSUE THREAD

**Issue by nomyfan** [f-person/git-blame.nvim#49]
It works on my mac but not Windows PC.

**Comment by f-person** [comment]
Could you please clarify?

**Comment by Nomyfan** [comment]
<img width="581" alt="Snipaste_2022-05-04_13-11-19" src="https://user-images.githubusercontent.com/19922814/166626070-09c2107e-7146-4b01-a567-90b0d6c172da.png">

On my Windows 10 machine, it shows "Not Committed Yet" for all lines.

**Comment by f-person** [comment]
Hmm, I wonder if this is related to line endings. Are there any errors in `:messasges`?

**Comment by Nomyfan** [comment]
There's nothing in `:messasges`.
 
I spent a while debugging, and I may get the reason, that's because `git.get_repo_root` isn't compatible with Windows.
<img width="1590" alt="Snipaste_2022-05-05_22-42-52" src="https://user-images.githubusercontent.com/19922814/166950386-091db75c-a042-466e-a7bb-ef5e9786a2a4.png">

In the case of above figure, when I hard code the repo root which should be `D:\Dev\Github\immer`, it works.

**Comment by f-person** [comment]
@Nomyfan can you please check if #48 fixes it for you?

**Comment by Nomyfan** [comment]
No, it doesn't help.

**Comment by Nomyfan** [comment]
I found [vim-fugitive](https://github.com/tpope/vim-fugitive)'s `:Git blame` works on Windows, but the Vim scripts code is kind of hard for me to read now. Maybe you can check out how it works.

**Comment by f-person** [comment]
Okie, I'll check it

**Comment by cpkio** [comment]
Maybe you should use something like
`local command = 'git --no-pager -C "' .. vim.fn.expand('%:p:h') .. '" blame -b -p -w --date relative --contents - ' .. filepath`, seems to be working for me. I dont see any reason going to root, just go to the directory of the file.

**Comment by f-person** [comment]
Fixed by #54. Kudos to @eriedaberrie!
