### ISSUE TITLE
Add configuration to ignore empty lines

### ISSUE THREAD

**Issue by broneks** [f-person/git-blame.nvim#91]
Currently, git blame will show for empty lines, which is not very useful and sort of distracting. It would be nice to have an option to configure this.

Suggestion:

```vim
let g:gitblame_ignore_empty_lines = true " default
```

**Comment by f-person** [comment]
Hi! I'm not sure it's a good idea to add this since lines are pretty much a part of git commits & blame messages. This can, however, be done with simple autocommands on the user side :)
(call `GitBlameDisable` when the cursor moves to an empty line and enable it back afterward)
 
Can you please elaborate on your use case? Do you have several empty lines next to each other?

**Comment by broneks** [comment]
Thanks for the advice, I'll try using an autocommand for this.
